#!/usr/bin/perl

# Copyright (c) 2026 Todd T. Fries <todd@fries.net>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

use strict;
use warnings;
use Getopt::Long;
use FindBin qw($Bin);
use lib "$Bin/../lib";
use SPF2CIDR;
use SPF2CIDR::Cache;

my %opts;
GetOptions(
    \%opts,
    'v|verbose+',
    'd|domfile=s',
    'o|output=s',
    'r|resolver=s',
    'w|watch',
    't|table=s',
    'h|help',
    'version',
) or usage();

if ($opts{version}) {
    print "spf2cidr $SPF2CIDR::VERSION\n"; exit 0;
}
usage() if $opts{h};

my $spf = SPF2CIDR->new(
    verbose => $opts{v} || 0,
    pf_table => $opts{t} || 'spf',
);

if ($opts{w}) {
    $spf->watch_log_and_whitelist(
        $opts{log} || undef,
        $opts{d} || '/etc/mail/spf-domains',
        $opts{t} || 'spf'
    );
    exit 0;
}

my @domains;
if (defined $ARGV[0]) {
    @domains = @ARGV;
} elsif ($opts{d} && -f $opts{d}) {
    open my $fh, '<', $opts{d} or die "open $opts{d}: $!";
    while (<$fh>) {
        s/#.*//; chomp; s/^\s+//; s/\s+$//;
        push @domains, $_ if length;
    }
    close $fh;
} else {
    usage("No domains or domfile given");
}

my $out = \*STDOUT;
if ($opts{o}) {
    open $out, '>', $opts{o} or die "open $opts{o}: $!";
}

$spf->process_domains(\@domains, $out);

sub usage {
    my $msg = shift;
    print STDERR "$msg\n\n" if $msg;
    print STDERR <<EOF;
Usage: spf2cidr [options] [domain [ip]] ...

Options:
  -v, --verbose       Increase verbosity (show expansions, queries)
  -d, --domfile=FILE  Read domains (and optional IPs) from FILE (default /etc/mail/spf-domains)
  -o, --output=FILE   Write output to FILE instead of stdout
  -w, --watch         Tail spamd log and auto-add authorized CIDRs to pf table on GREY
  -t, --table=NAME    pf table name for --watch (default "spf")
  -r, --resolver=IP   Use specific DNS resolver (future)
  -h, --help          This help
  --version

Examples:
  spf2cidr example.com
  spf2cidr "bounce.entrykeyid.com 156.70.46.238"
  spf2cidr -d /etc/mail/spf-domains -v
  spf2cidr -w -d /etc/mail/spf-domains -t spf-whitelist

See also: man pfctl, spamd(8), and the Perl module SPF2CIDR(3)
EOF
    my $ret = defined $msg ? 1 : 0;
    exit $ret;
}
